language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - npm test
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
    - secure: >-
        yu3EUol2vjCD2fCaQOnFwEU7CGD650h9aaYNYavbzLyKUy45P2liLp1SrcJwJc3qh2GCR/WGzJ3uWwMqDJuLPvtLYMbIKWKAb6aFjKEa5bo5LSvPQ5DhXO8+/J3w4BO/ukiBM/bztbvJen50eUYKrks4WgIwdjhz0QOdgdeYNpk7nz1CQ3MVy89Q9alPMckRC3SLJZuQh8yUUGbkn/r3R9arhT1OWytbnIjzezRpRaaBqp/AMhgc0YBHTyTrhZAPbMeh+KFfbQ40rTemtSKz+5SDQUfIfXgj34tTpX3K3en5QVOj/6uB41po+M1DN1a3nkKxLtJ1Ll6KQM9V3hrYZeTG4Cabq3i7vCfq6SRU8u5e9vKgwuwf63r5Bhy/IAMx4xv+XIO+HYkCmdzPhp6N6jf7whSDHdI+kAAx74xZpr7AkRl+JZYOcEzb2lAU09zBCvEgg7+7jxG3mmKi/7TrHlxwdBqbr6zzU+89tXvxykgCPN2+O4NdpiNF0BjqteSliSbWH5PtgiieFqjgjO/iA2YNT1m5SJWHp1KQZ1F6S7WOIo/4C+I3deLOI9TbljoeYD2f0+pXixQBfJ3wFBFjvm5eoSBZnsrmiWTub+Y/RtTcprOEZXukgahWL/451LtHmmze0Q4Kdoei8gdceOT6x/kV+o5JxvVYpenJu1zsnKQ=
    - secure: >-
        KY/yaeRZ6QF4p7KEHxZi4qs0Fbs3lcL9BHhjMIeYQdL2KdtYBknV8xO1JMGwfKKVbchkl7FlymeMZkDhPI1krr6RAlAvWGlfTycCorTMLMcIDi7fUemlAfhEfeig/KaDCvZv6K7GBwRK7k2L5V2pQaXoyICR8rONjguo5J/tOnHYMslcANNoetWRz/5k7IHMPYXz//6nfFIoXJQNzLrv0TLfJ6U6yZuz7fXs9nzsFb8vYNSilB2RblB7HKVkbNvw2bjWJoQ04k3xVj2gQvp4DSqfzDwmCUJvfRgVFXtafUDVnr6YiHoNEuCiL9F13O1dAECFpu5nkUB8l3ZyPaGUtDGJH7Tzjh7/davwfCBmKKCbqrd3dvthCpSxW5HQ3Ldwib6J/Rkia3JAISbOZET9PeuI+FBI2hUuGBaQaggzACtxEhidOBmb4L5KTxX+0bOx+tQj6jmZf3ab4acpUyo/WFSswoK3s1C5ih/BgZVjywmtnCq1WdFIKkIGBYbxNAMoZhpJoDeSGJbzX0Xr44erStdyTz2I6lkc9l5dVwl2Zw77cubZlfROiiOVnla+Zl6Xi/OopzY8N9xrX3btBmpmmGb5RgoQG6SeIA6dvYTsUPUaSc1NSXbgyRR8AhTpr+JN/uuR4Y2ChoI7jdHn2nBtcuxVUsn5T18ljm0LjQRe+LQ=
